const { test, expect } = require('@playwright/test');
const { startTestApp } = require('../helpers/saas');
let env;
test.beforeAll(async () => { env = await startTestApp(); });
test.afterAll(async () => { await env.close(); });
async function signup(page, name = 'Browser User') {
  const email = `browser-${Date.now()}-${Math.random().toString(36).slice(2)}@example.com`;
  await page.goto(env.base);
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Full name').fill(name);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Browser-password-93!');
  await page.getByLabel('Confirm password', { exact: true }).fill('Browser-password-93!');
  await page.getByRole('button', { name: 'Create free account' }).click();
  await expect(page.getByRole('heading', { name: 'Check your inbox.' })).toBeVisible();
  await page.getByLabel('Verification code', { exact: true }).fill(env.mailbox.findLast(m => m.to === email).code);
  await page.getByRole('button', { name: 'Verify email', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A home for your next idea.' })).toBeVisible();
  await page.getByLabel('Workspace / company name').fill('Sandbee Test Studio');
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await page.getByRole('button', { name: 'Go to dashboard' }).click();
  await expect(page.getByRole('heading', { name: `Hello, ${name.split(' ')[0]}.` })).toBeVisible();
  return email;
}
async function navigate(page, name) {
  const toggle = page.getByRole('button', { name: 'Toggle menu' });
  if (await toggle.isVisible()) await toggle.click();
  await page.getByRole('navigation').getByRole('button', { name, exact: true }).click();
}
test('signup, onboarding, key lifecycle, lookup, usage and login work end to end', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const email = await signup(page);
  await navigate(page, 'API keys');
  await page.getByRole('button', { name: 'Generate API key', exact: true }).click();
  const key = await page.getByTestId('new-api-key').textContent();
  expect(key).toMatch(/^sb_live_/);
  await navigate(page, 'Playground');
  await expect(page.getByTestId('new-api-key')).toHaveCount(0);
  await page.getByLabel('GST identification number').fill('09AAFPC6958E1ZN');
  await page.getByRole('button', { name: 'Run lookup' }).click();
  await expect(page.getByRole('heading', { name: 'Lookup successful' })).toBeVisible();
  await expect(page.getByText('Example Business', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Run lookup' }).click();
  await expect(page.getByText('Saved response', { exact: true })).toBeVisible();
  await navigate(page, 'Overview');
  await expect(page.locator('.stat').first().locator('strong')).toHaveText('2');
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await navigate(page, 'Documentation');
  await page.getByRole('button', { name: 'JavaScript', exact: true }).click();
  await expect(page.locator('.code-block')).toContainText('process.env.SANDBEE_API_KEY');
  await navigate(page, 'API keys');
  await page.getByRole('button', { name: 'Replace API key', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByTestId('new-api-key')).not.toHaveText(key);
  expect((await page.request.get(`${env.base}/api/v1/gstin/09AAFPC6958E1ZN`, { headers: { authorization: `Bearer ${key}` } })).status()).toBe(401);
  await page.getByRole('button', { name: 'Revoke key', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByText('No active key', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Browser-password-93!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Hello, Browser.' })).toBeVisible();
  expect(errors).toEqual([]);
});
test('mobile workspace stays within viewport and navigation works', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await signup(page, 'Mobile User');
  await expect(page.getByRole('button', { name: 'Toggle menu' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await navigate(page, 'Playground');
  await expect(page.getByRole('heading', { name: 'First, create your API key.' })).toBeVisible();
  await navigate(page, 'Settings');
  await expect(page.getByRole('heading', { name: 'Workspace settings' })).toBeVisible();
});
test('invalid login reports an error without entering the workspace', async ({ page }) => {
  await page.goto(env.base);
  await page.getByLabel('Email address').fill('missing@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Incorrect-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Email or password is incorrect');
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
});
test('workspace changes persist and password change signs out the user', async ({ page }) => {
  const email = await signup(page, 'Settings User');
  await navigate(page, 'Settings');
  await page.getByLabel('Workspace / company name').fill('Updated Studio');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Workspace updated.');
  await page.getByLabel('Current password', { exact: true }).fill('Browser-password-93!');
  await page.getByLabel('New password', { exact: true }).fill('Replacement-browser-934!');
  await page.getByRole('button', { name: 'Change password & sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Replacement-browser-934!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('.workspace strong')).toHaveText('Updated Studio');
});
