const { test, expect } = require('@playwright/test');
const { startTestApp } = require('../helpers/saas');
let env;
test.beforeAll(async()=>{env=await startTestApp();});
test.afterAll(async()=>{await env.close();});
test('guided onboarding verifies email and presents styled desktop and mobile setup', async({page})=>{
  await page.goto(env.base);
  await page.getByRole('button',{name:'Create an account',exact:true}).click();
  await page.getByLabel('Full name').fill('Kartik Desai');
  await page.getByLabel('Email address').fill('onboarding@example.test');
  await page.getByLabel('Password',{exact:true}).fill('Onboarding-password-18!');
  await page.getByLabel('Confirm password',{exact:true}).fill('Onboarding-password-18!');
  await page.screenshot({path:'test-results/signup-redesigned.png',fullPage:true});
  await page.getByRole('button',{name:'Create free account'}).click();
  await expect(page.getByRole('heading',{name:'Check your inbox.'})).toBeVisible();
  await expect(page.getByRole('button',{name:/Resend in/})).toBeDisabled();
  const code=env.mailbox.findLast(m=>m.to==='onboarding@example.test').code;
  await page.getByLabel('Verification code',{exact:true}).fill(code==='000000'?'111111':'000000');
  await page.getByRole('button',{name:'Verify email',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('incorrect');
  await page.reload();
  await expect(page.getByRole('heading',{name:'Check your inbox.'})).toBeVisible();
  await page.getByLabel('Verification code',{exact:true}).fill(code);
  await page.getByRole('button',{name:'Verify email',exact:true}).click();
  await expect(page.getByRole('heading',{name:'A home for your next idea.'})).toBeVisible();
  await page.getByLabel('Workspace / company name').fill('Sandbee Studio');
  await page.getByRole('radio',{name:/Verify businesses/}).check();
  await page.screenshot({path:'test-results/onboarding-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/onboarding-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Create workspace'}).click();
  await expect(page.getByRole('heading',{name:'Your workspace is ready.'})).toBeVisible();
  await page.getByRole('button',{name:'Go to dashboard'}).click();
  await expect(page.getByRole('heading',{name:'Hello, Kartik.'})).toBeVisible();
});
test('forgot password completes code verification, confirmation and fresh login',async({page})=>{
  const email='recovery-browser@example.test';
  const signed=await env.request('/api/auth/signup',{method:'POST',body:{name:'Recovery User',email,password:'Original-password-29!'}});
  const auth={cookie:signed.cookie,csrf:signed.body.csrfToken};
  await env.request('/api/auth/verification/confirm',{...auth,method:'POST',body:{code:env.mailbox.findLast(m=>m.to===email).code}});
  await env.request('/api/onboarding',{...auth,method:'POST',body:{company:'Recovery Studio',useCase:'development'}});
  await page.goto(env.base);
  await page.getByRole('button',{name:'Forgot password?',exact:true}).click();
  await page.getByLabel('Email address').fill(email);
  await page.getByRole('button',{name:'Send reset code'}).click();
  await expect(page.getByRole('heading',{name:'Check your email.'})).toBeVisible();
  await expect.poll(()=>env.mailbox.some(m=>m.to===email&&m.purpose==='reset')).toBe(true);
  const code=env.mailbox.findLast(m=>m.to===email&&m.purpose==='reset').code;
  await page.getByLabel('Verification code',{exact:true}).fill(code);
  await page.getByRole('button',{name:'Verify reset code'}).click();
  await expect(page.getByRole('heading',{name:'Choose a new password.'})).toBeVisible();
  await page.getByLabel('New password',{exact:true}).fill('Recovered-password-24!');
  await page.getByLabel('Confirm new password',{exact:true}).fill('Does-not-match-24!');
  await page.getByRole('button',{name:'Reset password',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('do not match');
  await page.getByLabel('Confirm new password',{exact:true}).fill('Recovered-password-24!');
  await page.getByRole('button',{name:'Reset password',exact:true}).click();
  await expect(page.getByRole('heading',{name:'You’re all set.'})).toBeVisible();
  await page.screenshot({path:'test-results/reset-success.png',fullPage:true});
  await page.getByRole('button',{name:'Back to sign in'}).click();
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password',{exact:true}).fill('Recovered-password-24!');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Hello, Recovery.'})).toBeVisible();
});
test('styled form validation and HTML upstream failures never show raw markup',async({page})=>{
  await page.goto(env.base);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Please enter email address');
  await page.getByLabel('Email address').fill('html-error@example.test');
  await page.getByLabel('Password',{exact:true}).fill('Some-password-129!');
  await page.route('**/api/auth/login',route=>route.fulfill({status:502,contentType:'text/html',body:'<html><h1>Proxy error and internal diagnostic</h1></html>'}));
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('alert')).toHaveText('We could not reach the service. Please try again in a moment.');
  await expect(page.locator('body')).not.toContainText('Proxy error');
});
